name: Build 3DS Homebrew

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install devkitPro & 3DS Toolchain
        uses: devkitPro/setup-devkitpro@v1
        with:
          dkp-packages: |
            3ds-dev
            3ds-curl
            3ds-bzip2
            3ds-libkhax

      - name: Download Makerom
        run: |
          sudo wget https://github.com
          sudo unzip makerom-v0.17-ubuntu_x86_64.zip -d /usr/local/bin
          sudo chmod +x /usr/local/bin/makerom

                - name: Compile Game
        run: |
          make clean
          make

      - name: Upload Finished Files
        uses: actions/upload-artifact@v4
        with:
          name: ctrHexenII-Build
          path: |
            *.cia
            *.3dsx
