name: Build 3DS Homebrew

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install 3DS Dependencies
        run: |
          dkp-pacman -Syu --noconfirm
          dkp-pacman -S 3ds-libkhax 3ds-curl 3ds-bzip2 3ds-dev --noconfirm

      - name: Compile Game
        run: |
          make clean
          make

      - name: Upload Finished Files
        uses: actions/upload-artifact@v4
        with:
          name: ctrHexenII-Build
          path: |
            *.cia
            *.3dsx
